/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-08 00:01:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" />\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/svg+xml\" href=\"assets/images/image 8.svg\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("  <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css\"\r\n");
      out.write("      integrity=\"sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\" />\r\n");
      out.write("<title>ViaVem</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<header class=\"header\">\r\n");
      out.write("			 <nav class=\"navbar navbar-expand-lg bg-light fixed-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("            <img src=\"assets/images/image 8.svg\" class=\"logo\" alt=\"logo\" />\r\n");
      out.write("            <span class=\"text-success\">Via</span>Vem\r\n");
      out.write("          </a>\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"navbar-toggler\"\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-toggle=\"collapse\"\r\n");
      out.write("            data-bs-target=\"#navbarNav\"\r\n");
      out.write("            aria-controls=\"navbarNav\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("            aria-label=\"Toggle navigation\"\r\n");
      out.write("          >\r\n");
      out.write("            <i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav mx-auto\">\r\n");
      out.write("           ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./components/menu.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("home", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("./index.jsp", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("usuarios", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("usuario", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("passagens", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("passagem", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("aeroportos", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("aeroporto", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"header_right\">\r\n");
      out.write("              <div class=\"text-lg-end\">\r\n");
      out.write("                <span class=\"text-success\">Fale</span> Conosco\r\n");
      out.write("                <span class=\"phone_no\">(79)9821-12123</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("	<main>\r\n");
      out.write("      <div\r\n");
      out.write("        id=\"carouselExampleCaptions\"\r\n");
      out.write("        class=\"carousel slide\"\r\n");
      out.write("        data-bs-ride=\"carousel\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("          <button\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("            data-bs-slide-to=\"0\"\r\n");
      out.write("            class=\"active\"\r\n");
      out.write("            aria-current=\"true\"\r\n");
      out.write("            aria-label=\"Slide 1\"\r\n");
      out.write("          ></button>\r\n");
      out.write("          <button\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("            data-bs-slide-to=\"1\"\r\n");
      out.write("            aria-label=\"Slide 2\"\r\n");
      out.write("          ></button>\r\n");
      out.write("          <button\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("            data-bs-slide-to=\"2\"\r\n");
      out.write("            aria-label=\"Slide 3\"\r\n");
      out.write("          ></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("          <div class=\"carousel-item active\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"assets/images/have-cameras-will-travel.jpg\"\r\n");
      out.write("              class=\"d-block w-100\"\r\n");
      out.write("              alt=\"cameras\"\r\n");
      out.write("            />\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("              <p class=\"text-bg-success\">A sua viagem!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"assets/images/antique-binoculars-and-map.jpg\"\r\n");
      out.write("              class=\"d-block w-100\"\r\n");
      out.write("              alt=\"...\"\r\n");
      out.write("            />\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("              <p class=\"text-bg-success\">As melhores ofertas!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"assets/images/travel-written-in-sand.jpg\"\r\n");
      out.write("              class=\"d-block w-100\"\r\n");
      out.write("              alt=\"...\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button\r\n");
      out.write("          class=\"carousel-control-prev\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("          data-bs-slide=\"prev\"\r\n");
      out.write("        >\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button\r\n");
      out.write("          class=\"carousel-control-next\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("          data-bs-slide=\"next\"\r\n");
      out.write("        >\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("      <section id=\"about\" class=\"bg-black\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12 col-12 bg\">\r\n");
      out.write("              <div class=\"about-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                  src=\"assets/images/rolling-suitcase-into-hotel.jpg\"\r\n");
      out.write("                  alt=\"travel\"\r\n");
      out.write("                  class=\"img-fluid\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8 col-md-12 col-12 ps-lg-5 mt-md-5\">\r\n");
      out.write("              <div class=\"about-text\">\r\n");
      out.write("                <h2 class=\"text-white\">\r\n");
      out.write("                  Nós temos o melhor serviço\r\n");
      out.write("                  <span class=\"text-success\">acredite!</span>\r\n");
      out.write("                </h2>\r\n");
      out.write("                <p class=\"text-secondary\">Sempre pensando em você!</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-fluid bg-dark text-light footer pt-1 mt-1\">\r\n");
      out.write("          <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("              <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h4 class=\"text-white mb-3\">\r\n");
      out.write("                  ViaVem <i class=\"fa fa-plane\" aria-hidden=\"true\"></i>\r\n");
      out.write("                </h4>\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-link text-white\"\r\n");
      out.write("                  >Endereço <i class=\"fa fa-map\" aria-hidden=\"true\"></i\r\n");
      out.write("                ></a>\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-link text-white\"\r\n");
      out.write("                  >Contato <i class=\"fa fa-whatsapp\" aria-hidden=\"true\"></i\r\n");
      out.write("                ></a>\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-link text-white\"\r\n");
      out.write("                  >Termos e Condições</a\r\n");
      out.write("                >\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-link text-white\">FAQ & HELP</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col lg-3 col-md-6\">\r\n");
      out.write("                <h4 class=\"text-white mb-3\">Sede</h4>\r\n");
      out.write("                <p class=\"mb-2\">\r\n");
      out.write("                  <i class=\"fa fa-location-arrow\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  São Cristovão-SE\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>	\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
